name: Checkout.com / Google UCP Sandbox
values:
  - key: merchantBaseUrl
    value: 'https://example.com'
  - key: ucp3dsExtensionVersion
    value: '2026-08-25'
  - key: authToken
    value: ''
  - key: partnerId
    value: ''
  - key: partnerApiKey
    value: ''
  - key: webhookSignatureInput
    value: ''
  - key: webhookSignature
    value: ''
  - key: webhookHash
    value: ''
  - key: checkoutSessionId
    value: ''
  - key: ckoBaseUrl
    value: 'https://cnxotvu6.api.sandbox.checkout.com'
  - key: ckoUcp3dsBaseUrl
    value: 'https://api.sandbox.checkout.com/agentic_commerce/ucp/3ds'
  - key: ckoPublicKey
    value: ''
  - key: ckoSecretKey
    value: ''
  - key: ckoProcessingChannelId
    value: pc_q3za5dznh56uljcsf6wrpfpqky
  - key: ckoTokenId
    value: ''
  - key: ckoUcp3dsUrl
    value: ''
color: 240
